// Generated by CoffeeScript 2.0.1
(function() {
  var gallery;

  gallery = document.getElementById('gallery');

  gallery.addEventListener('click', function(e) {
    var src, target;
    target = e.target;
    while (target.tagName !== 'A') {
      target = target.parentElement;
    }
    e.preventDefault();
    src = target.getAttribute('href');
    return this.querySelector('.photo--big img').setAttribute('src', src);
  });

  window.addEventListener('load', function() {
    var i, img, len, preview, previews, results;
    previews = gallery.querySelectorAll('.photo--preview');
    results = [];
    for (i = 0, len = previews.length; i < len; i++) {
      preview = previews[i];
      img = document.createElement('img');
      results.push(img.src = preview.getAttribute('href'));
    }
    return results;
  });

}).call(this);
